kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
    volume.kubernetes.io/selected-node: na46-knxk4-worker-0-l69nq
  selfLink: >-
    /api/v1/namespaces/fiap-grupo7-rm341751/persistentvolumeclaims/sample-db-grupo7-rm341751
  resourceVersion: '33796265'
  name: sample-db-grupo7-rm341751
  uid: f5d5f6aa-5ec7-4d1a-aeee-c639fdbf2134
  creationTimestamp: '2022-03-21T22:00:20Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2022-03-21T22:00:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:template': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:volumeMode': {}
    - manager: kube-scheduler
      operation: Update
      apiVersion: v1
      time: '2022-03-21T22:00:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:volume.kubernetes.io/selected-node': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-03-21T22:00:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
        'f:spec':
          'f:volumeName': {}
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
  namespace: fiap-grupo7-rm341751
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: db-grupo7-rm341751
    app.kubernetes.io/component: db-grupo7-rm341751
    app.kubernetes.io/instance: db-grupo7-rm341751
    template: postgresql-persistent-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-f5d5f6aa-5ec7-4d1a-aeee-c639fdbf2134
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi