apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiap-grupo7-rm341751
resources:
  - deployment/blog-grupo7-deployment.yml
  - deployment-config/sample-db-grupo7-rm341751.deploymentconfig.yml
  - hpa/hpa-blog-grupo7.yml
  - pvc/sample-db-grupo7-rm341751-pvc.yml
  - secret/sample-db-grupo7-rm341751.secret.yml
  - service/blog-django-grupo7-rm341751-py.yml
  - service/sample-db-grupo7-rm341751.yml
  - route/blog-ingress.route.yml