kind: Service
apiVersion: v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-instruqt/blog-django-py'
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /api/v1/namespaces/fiap-grupo7-rm341751/services/blog-django-grupo7-rm341751-py
  resourceVersion: '33784488'
  name: blog-django-grupo7-rm341751-py
  uid: 201a7b71-e411-4afc-bb23-60c126681e74
  creationTimestamp: '2022-03-21T21:47:09Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-03-21T21:47:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:sessionAffinity': {}
          'f:type': {}
  namespace: fiap-grupo7-rm341751
  labels:
    app: blog-django-grupo7-rm341751-py
    app.kubernetes.io/component: blog-django-grupo7-rm341751-py
    app.kubernetes.io/instance: blog-django-grupo7-rm341751-py
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-django-py-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: blog-django-grupo7-rm341751-py
    deploymentconfig: blog-django-grupo7-rm341751-py
  clusterIP: 172.30.65.229
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}