kind: Secret
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  selfLink: /api/v1/namespaces/fiap-grupo7-rm341751/secrets/sample-db-grupo7-rm341751
  resourceVersion: '33796161'
  name: sample-db-grupo7-rm341751
  uid: b019de43-3b19-41ca-9c69-981f86624cd3
  creationTimestamp: '2022-03-21T22:00:20Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2022-03-21T22:00:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:template': {}
        'f:type': {}
  namespace: fiap-grupo7-rm341751
  labels:
    app: db-grupo7-rm341751
    app.kubernetes.io/component: db-grupo7-rm341751
    app.kubernetes.io/instance: db-grupo7-rm341751
    template: postgresql-persistent-template
data:
  database-name: c2FtcGxlZGI=
  database-password: c2FtcGxlZGI=
  database-user: c2FtcGxlZGI=
type: Opaque
